export const PacketTypes: PacketType = {
  0: "PING",
  1: "PONG",
  2: "CONNECTION_COUNT",
  3: "RATE_LIMITED",
  4: "LOGIN",
  5: "LOGIN_SUCCESS",
  6: "LOGIN_FAILED",
  7: "LOAD_MAP",
  8: "TIME_SYNC",
  9: "MOVEXY",
  10: "AUTH",
  11: "LOGOUT",
  12: "DISCONNECT",
};
